blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions & Q&A
    url: https://github.com/imvicky69/infyn-dl/discussions
    about: Ask questions, share ideas, and discuss with the community.
